Hw01 is completed
aleks-papushin/otus_go_hw01 pull request #1
Opened 2024-03-31 15:47 UTC by aleks-papushin

## Домашнее задание №1 «Hello, OTUS!»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я использовал `stringutil.Reverse`.
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - main.go ~12 строк

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Используется `stringutil` - 4 балла
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-03-31 16:18 UTC, vladislavmass requested changes

2024-03-31 16:18 UTC, vladislavmass commented on hw01_hello_otus/go.mod
> +module github.com/aleks-papushin/otus_go_hw01
Неверное имя модуля. Верное имя модуля в данном случае `github.com/aleks-papushin/otus_go_hw01/hw01_hello_otus`

2024-03-31 16:18 UTC, vladislavmass commented on hw01_hello_otus/.golangci.yml
> +  gci-lint:
Не надо менять правила работы линтера. Прохождение изначально заданных линтеров это часть условия для приема дз

2024-03-31 17:02 UTC, aleks-papushin commented on hw01_hello_otus/go.mod
> +module github.com/aleks-papushin/otus_go_hw01
Понял. То есть имя модуля должно включать не только имя репозитория, но и имя ветки?

2024-03-31 17:03 UTC, aleks-papushin commented on hw01_hello_otus/.golangci.yml
> +  gci-lint:
Тогда не совсем очевидно, что нужно сделать.

2024-03-31 17:11 UTC, vladislavmass requested changes

2024-03-31 17:11 UTC, vladislavmass commented on hw01_hello_otus/go.mod
> +module github.com/aleks-papushin/otus_go_hw01
Не ветки, а каталога в репозитарии где лежит данный модуль.

2024-03-31 17:11 UTC, vladislavmass commented on hw01_hello_otus/.golangci.yml
> +  gci-lint:
Скорее всего нужно добавить пустую строку между 4 и 5 строкой в main.go. Если не поможет, то запустите линтер с ключем -- fix. Примерно вот так `golangci-lint run --fix .`

2024-03-31 21:06 UTC, aleks-papushin commented on hw01_hello_otus/.golangci.yml
> +  gci-lint:
Да, пустая строка помогла

2024-04-01 03:05 UTC, vladislavmass approved these changes

2024-04-02 07:41 UTC, merged